development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: symphonyschool123@gmail.com
  :password: Muruga11!!
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: symphonyschool123@gmail.com
  :password: Muruga11!!
  :enable_starttls_auto: true
